java_binary(
    name = "simple_download_file",
    srcs = ["src/main/java/SimpleDownloadFile.java"],
    main_class = "com.google.devtools.build.tools.SimpleDownloadFile",
    deps = [
        "//api",
        "//core:util",
        "//netty",
        "//third_party/googleapis:google_bytestream_bytestream_java_grpc",
        "//third_party/googleapis:google_bytestream_bytestream_java_proto",
        "//third_party/remoteapis:build_bazel_remote_execution_v2_remote_execution_java_proto",
    ],
)
